#
# settings related to recompiling and reruning app when source changes
#

[app]
    mode = "release"
    data_path = "/stock/data"   # 数据的存放路径

    [app.logger]
        level = "DEBUG"
        name = "cquant"

[extend]
    # 扩展参数
    [extend.files]
        stock_day_fixed = "/history/fixed/%s.csv.zip"        # 每只股票的后复权价
        stock_day_ma_price = "/history/ma_price/%s.csv.zip"  # 每只股票后复权价的平均移动均线
        stock_day_ma_volume = "/history/ma_vol/%s.csv.zip"   # 每只股票交易量的平均移动均线
        stock_day_pe = "/history/pe/%s.csv.zip"              # 每只股票的平均移动均线
        stock_day_pb = "/history/pb/%s.csv.zip"              # 每只股票的平均移动均线

# 通达信一些配置参数
[tdx]
    [tdx.urls]
        stock_fin = "http://down.tdx.com.cn:8001/fin"
        fin_list_file = "gpcw.txt"  # 财务数据文件列表
    [tdx.files]
        calendar = "/base/calendar.csv.zip"                  # 股票交易日历
        stock_list = "/base/stocks.csv.zip"                  # 通达信商品(股票、基金、指数、债券等)列表信息
        stock_bonus = "/base/bonus.csv.zip"                  # 存放每只股票的分红配股信息
        stock_day = "/history/days/"                         # 每只股票的日K数据
        stock_min = "/history/mins/"                         # 每只股票的5分钟数据
        stock_report = "/report/"                          # 存放每只股票的财务报告
    [tdx.server]
        data_host = "121.14.110.200:443"
        monitor_host= "121.14.110.200:443"
        
# 同花顺的一些配置参数
[thsi]
    [thsi.urls]
        server_time = "https://s.thsi.cn/js/chameleon/time.%d.js"   # 用于更新同花顺服务器时间解密cookie信息
        report_time = "http://data.10jqka.com.cn/financial/yypl/date/%s/board/ALL/field/stockcode/order/DESC/page/%d/ajax/1/"

    [thsi.files]
        report_time = "/report/"                          # 财务披露时间数据的存放未知
        
#
# db settings
#
[db]
    driver = "mysql"
    source = "root:123456@localhost/cquant?charset=utf8&parseTime=True&loc=Local"
    debug = false
